# Generated by Django 3.0.5 on 2020-05-22 02:10

import annonce.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annonce_demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tele', models.IntegerField()),
                ('ville', models.CharField(max_length=30)),
                ('bagages', models.CharField(choices=[('pas_bgg', 'pas de bagages'), ('bgg_normal', 'bagages normal'), ('bgg_lourd', 'bagages lourd'), ('bgg_tr_lourd', 'bagages trés lourd')], max_length=12)),
                ('comment', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_personnes', models.IntegerField(validators=[annonce.models.validate_num])),
            ],
            options={
                'ordering': ('-created', 'ville'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='annonce_offrir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tele', models.IntegerField()),
                ('ville', models.CharField(max_length=30)),
                ('bagages', models.CharField(choices=[('pas_bgg', 'pas de bagages'), ('bgg_normal', 'bagages normal'), ('bgg_lourd', 'bagages lourd'), ('bgg_tr_lourd', 'bagages trés lourd')], max_length=12)),
                ('comment', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_places', models.IntegerField(validators=[annonce.models.validate_num])),
                ('car_model', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created', 'ville'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='fiche_annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_distination', models.CharField(max_length=50)),
                ('lieu_depart', models.CharField(max_length=50)),
                ('lieu_arrive', models.CharField(max_length=50)),
                ('date_depart', models.DateTimeField(max_length=50)),
                ('date_arrive', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tele', models.IntegerField()),
                ('ville', models.CharField(max_length=30)),
                ('bagages', models.CharField(choices=[('pas_bgg', 'pas de bagages'), ('bgg_normal', 'bagages normal'), ('bgg_lourd', 'bagages lourd'), ('bgg_tr_lourd', 'bagages trés lourd')], max_length=12)),
                ('comment', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('lvr', 'livreur'), ('bgg', 'bagages')], max_length=3)),
            ],
            options={
                'ordering': ('-created', 'ville'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='annonce_ville',
            fields=[
                ('annonce_demande_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annonce.annonce_demande')),
                ('lieu', models.CharField(max_length=30)),
                ('distination', models.CharField(max_length=30)),
                ('num_places', models.IntegerField(validators=[annonce.models.validate_num])),
                ('date_depart', models.DateField(max_length=50)),
            ],
            options={
                'ordering': ('-created', 'ville'),
                'abstract': False,
            },
            bases=('annonce.annonce_demande',),
        ),
    ]
