# Generated by Django 3.0.5 on 2020-05-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce_demande',
            name='visiblty',
        ),
        migrations.RemoveField(
            model_name='annonce_offrir',
            name='visiblty',
        ),
        migrations.RemoveField(
            model_name='fiche_annonce',
            name='visiblty',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='visiblty',
        ),
    ]
