# Generated by Django 3.0.5 on 2020-05-22 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livraison',
            name='fiche',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annonce.fiche_annonce'),
        ),
        migrations.AddField(
            model_name='annonce_offrir',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce_offrir',
            name='fiche',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annonce.fiche_annonce'),
        ),
        migrations.AddField(
            model_name='annonce_demande',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce_demande',
            name='fiche',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annonce.fiche_annonce'),
        ),
    ]
