# Generated by Django 3.0.5 on 2020-05-16 01:02

import annonce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_auto_20200511_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce_demande',
            name='num_tele',
            field=models.IntegerField(validators=[annonce.models.annonce.validate_tele]),
        ),
        migrations.AlterField(
            model_name='annonce_offrir',
            name='num_tele',
            field=models.IntegerField(validators=[annonce.models.annonce.validate_tele]),
        ),
        migrations.AlterField(
            model_name='fiche_annonce',
            name='date_arrive',
            field=models.DateTimeField(max_length=50, validators=[annonce.models.fiche_annonce.validate_date]),
        ),
        migrations.AlterField(
            model_name='fiche_annonce',
            name='date_depart',
            field=models.DateTimeField(max_length=50, validators=[annonce.models.fiche_annonce.validate_date]),
        ),
        migrations.AlterField(
            model_name='fiche_annonce',
            name='lieu_arrive',
            field=models.CharField(max_length=50, validators=[annonce.models.fiche_annonce.validate_lieu]),
        ),
        migrations.AlterField(
            model_name='fiche_annonce',
            name='lieu_depart',
            field=models.CharField(max_length=50, validators=[annonce.models.fiche_annonce.validate_lieu]),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='num_tele',
            field=models.IntegerField(validators=[annonce.models.annonce.validate_tele]),
        ),
    ]
