# Generated by Django 3.0.5 on 2020-05-10 23:03

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[user.models.compte.validate_name])),
                ('prénom', models.CharField(max_length=50, validators=[user.models.compte.validate_name])),
                ('psudo', models.SlugField(unique=True)),
                ('image_profile', models.ImageField(upload_to='')),
                ('CIN', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('MDP', models.CharField(max_length=30, validators=[user.models.compte.validate_mdp])),
                ('visiblty', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('email', 'CIN', 'psudo')},
            },
        ),
        migrations.CreateModel(
            name='reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamation', models.TextField()),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.compte')),
            ],
        ),
    ]
