# Generated by Django 3.0.5 on 2020-05-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='visiblty',
        ),
        migrations.AlterField(
            model_name='compte',
            name='image_profile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
