# Generated by Django 3.0.5 on 2020-05-16 01:02

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200511_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='CIN',
            field=models.CharField(max_length=10, validators=[user.models.compte.validate_cin]),
        ),
    ]
